version: '3.7'

services:
  backend-challenge-api:
    image: backend-challenge-api
    container_name: backend-challenge-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"        
    restart: always
    privileged: true
    tty: true